export const LXX_CATALOG = Object.freeze([
  {
    workId: "tlg001",
    id: "genesis",
    code: "Gen",
    titleGreek: "Γένεσις",
    titleEnglish: "Genesis",
  },
  {
    workId: "tlg002",
    id: "exodus",
    code: "Exod",
    titleGreek: "Ἔξοδος",
    titleEnglish: "Exodus",
  },
  {
    workId: "tlg003",
    id: "leviticus",
    code: "Lev",
    titleGreek: "Λευϊτικόν",
    titleEnglish: "Leviticus",
  },
  {
    workId: "tlg004",
    id: "numbers",
    code: "Num",
    titleGreek: "Ἀριθμοί",
    titleEnglish: "Numbers",
  },
  {
    workId: "tlg005",
    id: "deuteronomy",
    code: "Deut",
    titleGreek: "Δευτερονόμιον",
    titleEnglish: "Deuteronomy",
  },
  {
    workId: "tlg006",
    id: "joshua",
    code: "Josh",
    titleGreek: "Ἰησοῦς Ναυῆ",
    titleEnglish: "Joshua",
  },
  {
    workId: "tlg008",
    id: "judges",
    code: "Judg",
    titleGreek: "Κριταί",
    titleEnglish: "Judges",
  },
  {
    workId: "tlg010",
    id: "ruth",
    code: "Ruth",
    titleGreek: "Ῥούθ",
    titleEnglish: "Ruth",
  },
  {
    workId: "tlg011",
    id: "1-kingdoms",
    code: "1 Kgdms",
    titleGreek: "Βασιλειῶν Αʹ",
    titleEnglish: "1 Kingdoms",
  },
  {
    workId: "tlg012",
    id: "2-kingdoms",
    code: "2 Kgdms",
    titleGreek: "Βασιλειῶν Βʹ",
    titleEnglish: "2 Kingdoms",
  },
  {
    workId: "tlg013",
    id: "3-kingdoms",
    code: "3 Kgdms",
    titleGreek: "Βασιλειῶν Γʹ",
    titleEnglish: "3 Kingdoms",
  },
  {
    workId: "tlg014",
    id: "4-kingdoms",
    code: "4 Kgdms",
    titleGreek: "Βασιλειῶν Δʹ",
    titleEnglish: "4 Kingdoms",
  },
  {
    workId: "tlg015",
    id: "1-chronicles",
    code: "1 Chr",
    titleGreek: "Παραλειπομένων Αʹ",
    titleEnglish: "1 Chronicles",
  },
  {
    workId: "tlg016",
    id: "2-chronicles",
    code: "2 Chr",
    titleGreek: "Παραλειπομένων Βʹ",
    titleEnglish: "2 Chronicles",
  },
  {
    workId: "tlg017",
    id: "1-esdras",
    code: "1 Esd",
    titleGreek: "Ἔσδρας Αʹ",
    titleEnglish: "1 Esdras",
  },
  {
    workId: "tlg018",
    id: "2-esdras",
    code: "2 Esd",
    titleGreek: "Ἔσδρας Βʹ",
    titleEnglish: "2 Esdras",
  },
  {
    workId: "tlg019",
    id: "esther",
    code: "Esth",
    titleGreek: "Ἐσθήρ",
    titleEnglish: "Esther",
  },
  {
    workId: "tlg020",
    id: "judith",
    code: "Jdt",
    titleGreek: "Ἰουδίθ",
    titleEnglish: "Judith",
  },
  {
    workId: "tlg021",
    id: "tobit",
    code: "Tob",
    titleGreek: "Τωβίτ",
    titleEnglish: "Tobit",
  },
  {
    workId: "tlg023",
    id: "1-maccabees",
    code: "1 Macc",
    titleGreek: "Μακκαβαίων Αʹ",
    titleEnglish: "1 Maccabees",
  },
  {
    workId: "tlg024",
    id: "2-maccabees",
    code: "2 Macc",
    titleGreek: "Μακκαβαίων Βʹ",
    titleEnglish: "2 Maccabees",
  },
  {
    workId: "tlg025",
    id: "3-maccabees",
    code: "3 Macc",
    titleGreek: "Μακκαβαίων Γʹ",
    titleEnglish: "3 Maccabees",
  },
  {
    workId: "tlg026",
    id: "4-maccabees",
    code: "4 Macc",
    titleGreek: "Μακκαβαίων Δʹ",
    titleEnglish: "4 Maccabees",
  },
  {
    workId: "tlg027",
    id: "psalms",
    code: "Ps",
    titleGreek: "Ψαλμοί",
    titleEnglish: "Psalms",
  },
  {
    workId: "tlg028",
    id: "odes",
    code: "Odes",
    titleGreek: "Ὠδαί",
    titleEnglish: "Odes",
  },
  {
    workId: "tlg029",
    id: "proverbs",
    code: "Prov",
    titleGreek: "Παροιμίαι",
    titleEnglish: "Proverbs",
  },
  {
    workId: "tlg031",
    id: "song-of-songs",
    code: "Song",
    titleGreek: "Ἆσμα Ἀσμάτων",
    titleEnglish: "Song of Songs",
  },
  {
    workId: "tlg032",
    id: "job",
    code: "Job",
    titleGreek: "Ἰώβ",
    titleEnglish: "Job",
  },
  {
    workId: "tlg033",
    id: "wisdom",
    code: "Wis",
    titleGreek: "Σοφία Σαλομῶντος",
    titleEnglish: "Wisdom of Solomon",
  },
  {
    workId: "tlg034",
    id: "sirach",
    code: "Sir",
    titleGreek: "Σοφία Σιράχ",
    titleEnglish: "Sirach",
  },
  {
    workId: "tlg035",
    id: "psalms-of-solomon",
    code: "Pss Sol",
    titleGreek: "Ψαλμοὶ Σαλομῶντος",
    titleEnglish: "Psalms of Solomon",
  },
  {
    workId: "tlg036",
    id: "hosea",
    code: "Hos",
    titleGreek: "Ὡσηέ",
    titleEnglish: "Hosea",
  },
  {
    workId: "tlg037",
    id: "amos",
    code: "Amos",
    titleGreek: "Ἀμώς",
    titleEnglish: "Amos",
  },
  {
    workId: "tlg038",
    id: "micah",
    code: "Mic",
    titleGreek: "Μιχαίας",
    titleEnglish: "Micah",
  },
  {
    workId: "tlg039",
    id: "joel",
    code: "Joel",
    titleGreek: "Ἰωήλ",
    titleEnglish: "Joel",
  },
  {
    workId: "tlg040",
    id: "obadiah",
    code: "Obad",
    titleGreek: "Ὀβδιού",
    titleEnglish: "Obadiah",
  },
  {
    workId: "tlg041",
    id: "jonah",
    code: "Jonah",
    titleGreek: "Ἰωνᾶς",
    titleEnglish: "Jonah",
  },
  {
    workId: "tlg042",
    id: "nahum",
    code: "Nah",
    titleGreek: "Ναούμ",
    titleEnglish: "Nahum",
  },
  {
    workId: "tlg043",
    id: "habakkuk",
    code: "Hab",
    titleGreek: "Ἀμβακούμ",
    titleEnglish: "Habakkuk",
  },
  {
    workId: "tlg044",
    id: "zephaniah",
    code: "Zeph",
    titleGreek: "Σοφονίας",
    titleEnglish: "Zephaniah",
  },
  {
    workId: "tlg045",
    id: "haggai",
    code: "Hag",
    titleGreek: "Ἀγγαῖος",
    titleEnglish: "Haggai",
  },
  {
    workId: "tlg046",
    id: "zechariah",
    code: "Zech",
    titleGreek: "Ζαχαρίας",
    titleEnglish: "Zechariah",
  },
  {
    workId: "tlg047",
    id: "malachi",
    code: "Mal",
    titleGreek: "Μαλαχίας",
    titleEnglish: "Malachi",
  },
  {
    workId: "tlg048",
    id: "isaiah",
    code: "Isa",
    titleGreek: "Ἠσαΐας",
    titleEnglish: "Isaiah",
  },
  {
    workId: "tlg049",
    id: "jeremiah",
    code: "Jer",
    titleGreek: "Ἱερεμίας",
    titleEnglish: "Jeremiah",
  },
  {
    workId: "tlg050",
    id: "baruch",
    code: "Bar",
    titleGreek: "Βαρούχ",
    titleEnglish: "Baruch",
  },
  {
    workId: "tlg051",
    id: "lamentations",
    code: "Lam",
    titleGreek: "Θρῆνοι",
    titleEnglish: "Lamentations",
  },
  {
    workId: "tlg052",
    id: "letter-of-jeremiah",
    code: "Ep Jer",
    titleGreek: "Ἐπιστολὴ Ἰερεμίου",
    titleEnglish: "Letter of Jeremiah",
  },
  {
    workId: "tlg053",
    id: "ezekiel",
    code: "Ezek",
    titleGreek: "Ἰεζεκιήλ",
    titleEnglish: "Ezekiel",
  },
  {
    workId: "tlg054",
    id: "susanna-old-greek",
    code: "Sus OG",
    titleGreek: "Σουσάννα (Οʹ)",
    titleEnglish: "Susanna · Old Greek",
  },
  {
    workId: "tlg055",
    id: "susanna-theodotion",
    code: "Sus Th",
    titleGreek: "Σουσάννα (Θʹ)",
    titleEnglish: "Susanna · Theodotion",
  },
  {
    workId: "tlg056",
    id: "daniel-old-greek",
    code: "Dan OG",
    titleGreek: "Δανιήλ (Οʹ)",
    titleEnglish: "Daniel · Old Greek",
  },
  {
    workId: "tlg057",
    id: "daniel-theodotion",
    code: "Dan Th",
    titleGreek: "Δανιήλ (Θʹ)",
    titleEnglish: "Daniel · Theodotion",
  },
  {
    workId: "tlg058",
    id: "bel-and-the-dragon-old-greek",
    code: "Bel OG",
    titleGreek: "Βὴλ καὶ Δράκων (Οʹ)",
    titleEnglish: "Bel and the Dragon · Old Greek",
  },
  {
    workId: "tlg059",
    id: "bel-and-the-dragon-theodotion",
    code: "Bel Th",
    titleGreek: "Βὴλ καὶ Δράκων (Θʹ)",
    titleEnglish: "Bel and the Dragon · Theodotion",
  },
]);
